---
- name: Disable root and password login
  hosts: prepare
  gather_facts: true
  ignore_unreachable: true
  tasks:
    - name: Disable password login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: ^PasswordAuthentication
        line: PasswordAuthentication no
      notify: Restart SSHd

    - name: Disable root login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: ^PermitRootLogin
        line: PermitRootLogin no
      notify: Restart SSHd

  handlers:
    - name: Restart SSHd
      ansible.builtin.service:
        name: ssh
        state: restarted
