website:
  hosts:
    mcbrawl.ru:
      ansible_host: 45.8.99.84

prepare:
  vars:
    ansible_user: root
    new_user: automation
    new_user_group: automation
  children:

docker:
  vars:
    ansible_user: automation
  children:
    webservers_traefik:
      children:
        website:
